services:
  - type: postgres
    name: taskapp-db
    plan: starter
    env: docker
    databaseName: taskapp

  - type: web_service
    name: taskapp
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: taskapp-db
          property: connectionString
      - key: JWT_SECRET
        value: please-change-me-to-a-long-random-string-in-prod
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://rival-task-management-app.onrender.com
      - key: COOKIE_SECURE
        value: "true"
      - key: NEXT_PUBLIC_API_URL
        value: /api
